### ISSUE TITLE
Can't pass login screen

### ISSUE THREAD

**Issue by esQmo** [forntoh/MBOASSIKOLOPATH#15]
Nothing seems to be working when choosing either facebook login or Google login. There seems to be a screen showing up then fades. Any documentation on how to make it work? Wanted to explore your project because I'm working on a similar project too.

**Comment by forntoh** [comment]
That is because you're building the app on your pc and you need to supply a debug key SHA to firebase for google sign-in to work. 

If you want to test it use the signed APK which I generated here 👉 [mboa_v1.0.0-alpha04](https://github.com/forntoh/MBOASSIKOLOPATH/releases/tag/v1.0.0-alpha04)  or clone the project and configure your own google log-in (with your credentials)

**Comment by esQmo** [comment]
Well, thanks. Tried he unsigned APK but the app crashes on main screen after the onboarding screen finishes
